sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mgnUndEQ1jNQuIdFKaiAYBmqhQifFv++rLl060/0V3jfm7sTxcIs3jV6yx3oczhtICuXkZSbYk6XeYzys9dUI4smujTxjB6EiUHyEyuzDtTMPSJUg7CS4wbrelQUdcpMgogz3cV40ZXqU/8SOkzx9VFUwRNkOhNhHI5Cp051h2GP9M+9ukP12q0aumyOF4rx1WIY1VrTdNUapUFm6ShKPFNL3DLb9rWMqAD2Fqo03epYJvN56ShKhvYBmZ65XTVrT4kzpytGzlU9HBspHbqOwVV6PZ+Wx3WW1Q5iUCdeLrbzQGAyB19OuMhwdAs2XcJfDbDgKwVJi1U9KahGylbDMno/yQwefMJrOxB5PDUIRLDef7mPS0Rt3nTRg4F68eJSFhltvrcHrzoBUr3WKNomyzybfZwjmnGxW2O/InUiV7J8PWQiPzDRPw5JzHYy5bzpxKRh6ajfCfyl9frIueOChbEgMRGSxsqrE4jsWPGIeV/zsgOH9Va3PRfSo2utLNTVJcN5M1dfYolaTdWLk/ec93LLZBWjuL7s4HdezGPUQ/d+cgkUWwkrwpzazbJSyS0c/X105LkXg2Q6t/4z99lK5IpOdfDCand0nn6ClRcCwAFu26hJ7aQUMp69gXSLq4yfOcv510GrlA8n/0uLkNyU5KqeZReqSnOSiMDN1/UYO8E=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Rise-of-David-Levinsky_2803
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy